-- Z-Anatomy integration for the rehabilitation / fitness app.
-- Apply after database/wger_schema.sql.
-- Z-Anatomy model/data layer is CC BY-SA 4.0. Keep attribution and derivative
-- 3D assets separate from app-owned rehabilitation content.

ALTER TABLE public.rehab_exercise_metadata
  ADD COLUMN IF NOT EXISTS activation TEXT,
  ADD COLUMN IF NOT EXISTS release TEXT,
  ADD COLUMN IF NOT EXISTS mobility TEXT,
  ADD COLUMN IF NOT EXISTS animation TEXT,
  ADD COLUMN IF NOT EXISTS progression TEXT,
  ADD COLUMN IF NOT EXISTS regression TEXT,
  ADD COLUMN IF NOT EXISTS posture_tags_text TEXT,
  ADD COLUMN IF NOT EXISTS difficulty_text TEXT,
  ADD COLUMN IF NOT EXISTS common_mistakes_text TEXT,
  ADD COLUMN IF NOT EXISTS contraindications_text TEXT;

CREATE TABLE IF NOT EXISTS public.z_anatomy_terms (
  ta2_code TEXT PRIMARY KEY,
  ta2_id INTEGER,
  name_en TEXT NOT NULL,
  name_latin TEXT,
  name_fr TEXT,
  name_es TEXT,
  name_pt TEXT,
  name_it TEXT,
  name_fa TEXT,
  source_repository TEXT NOT NULL DEFAULT 'Z-Anatomy/Models-of-human-anatomy',
  source_license TEXT NOT NULL DEFAULT 'CC BY-SA 4.0',
  raw_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_z_anatomy_terms_ta2_id ON public.z_anatomy_terms(ta2_id);
CREATE INDEX IF NOT EXISTS idx_z_anatomy_terms_name_en ON public.z_anatomy_terms(lower(name_en));
CREATE INDEX IF NOT EXISTS idx_z_anatomy_terms_name_latin ON public.z_anatomy_terms(lower(name_latin));

CREATE TABLE IF NOT EXISTS public.z_anatomy_assets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_key TEXT NOT NULL UNIQUE,
  asset_type TEXT NOT NULL CHECK (asset_type IN ('source_blend','source_archive','glb','gltf','fbx','manifest','thumbnail','other')),
  anatomical_system TEXT,
  source_url TEXT,
  storage_path TEXT,
  public_url TEXT,
  source_repository TEXT NOT NULL DEFAULT 'Z-Anatomy/Models-of-human-anatomy',
  source_version TEXT,
  license TEXT NOT NULL DEFAULT 'CC BY-SA 4.0',
  attribution TEXT NOT NULL,
  derivative_notice TEXT,
  checksum_sha256 TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.z_anatomy_meshes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mesh_name TEXT NOT NULL,
  glb_node_name TEXT,
  ta2_code TEXT REFERENCES public.z_anatomy_terms(ta2_code) ON DELETE SET NULL,
  anatomical_system TEXT,
  body_region TEXT,
  laterality TEXT CHECK (laterality IS NULL OR laterality IN ('left','right','midline','bilateral','unknown')),
  asset_id BIGINT REFERENCES public.z_anatomy_assets(id) ON DELETE SET NULL,
  is_clickable BOOLEAN NOT NULL DEFAULT TRUE,
  name_zh_override TEXT,
  synonyms TEXT[] NOT NULL DEFAULT '{}',
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(mesh_name, asset_id)
);

CREATE INDEX IF NOT EXISTS idx_z_anatomy_meshes_ta2_code ON public.z_anatomy_meshes(ta2_code);
CREATE INDEX IF NOT EXISTS idx_z_anatomy_meshes_system ON public.z_anatomy_meshes(anatomical_system);
CREATE INDEX IF NOT EXISTS idx_z_anatomy_meshes_body_region ON public.z_anatomy_meshes(body_region);
CREATE INDEX IF NOT EXISTS idx_z_anatomy_meshes_synonyms ON public.z_anatomy_meshes USING GIN(synonyms);

CREATE TABLE IF NOT EXISTS public.z_anatomy_wger_muscle_map (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wger_muscle_id BIGINT NOT NULL REFERENCES public.wger_muscles(id) ON DELETE CASCADE,
  ta2_code TEXT REFERENCES public.z_anatomy_terms(ta2_code) ON DELETE SET NULL,
  mesh_id BIGINT REFERENCES public.z_anatomy_meshes(id) ON DELETE CASCADE,
  match_type TEXT NOT NULL DEFAULT 'manual' CHECK (match_type IN ('manual','exact_name','alias','reviewed_auto')),
  confidence NUMERIC(4,3) CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
  notes TEXT,
  is_primary BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_zawmm_wger_code_mesh
  ON public.z_anatomy_wger_muscle_map(wger_muscle_id, ta2_code, mesh_id) NULLS NOT DISTINCT;
CREATE INDEX IF NOT EXISTS idx_zawmm_wger ON public.z_anatomy_wger_muscle_map(wger_muscle_id);
CREATE INDEX IF NOT EXISTS idx_zawmm_ta2_code ON public.z_anatomy_wger_muscle_map(ta2_code);
CREATE INDEX IF NOT EXISTS idx_zawmm_mesh ON public.z_anatomy_wger_muscle_map(mesh_id);

CREATE TABLE IF NOT EXISTS public.z_anatomy_sync_state (
  resource TEXT PRIMARY KEY,
  last_started_at TIMESTAMPTZ,
  last_completed_at TIMESTAMPTZ,
  last_status TEXT,
  records_synced BIGINT NOT NULL DEFAULT 0,
  error_message TEXT
);

CREATE TABLE IF NOT EXISTS public.z_anatomy_sync_config (
  id SMALLINT PRIMARY KEY CHECK (id = 1),
  token TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.z_anatomy_terms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.z_anatomy_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.z_anatomy_meshes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.z_anatomy_wger_muscle_map ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.z_anatomy_sync_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.z_anatomy_sync_config ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.z_anatomy_terms, public.z_anatomy_assets,
  public.z_anatomy_meshes, public.z_anatomy_wger_muscle_map,
  public.z_anatomy_sync_state, public.z_anatomy_sync_config
FROM anon, authenticated;

GRANT SELECT ON public.z_anatomy_terms, public.z_anatomy_assets,
  public.z_anatomy_meshes, public.z_anatomy_wger_muscle_map
TO anon, authenticated;

DROP POLICY IF EXISTS "read z anatomy terms" ON public.z_anatomy_terms;
CREATE POLICY "read z anatomy terms" ON public.z_anatomy_terms FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "read z anatomy assets" ON public.z_anatomy_assets;
CREATE POLICY "read z anatomy assets" ON public.z_anatomy_assets FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "read z anatomy meshes" ON public.z_anatomy_meshes;
CREATE POLICY "read z anatomy meshes" ON public.z_anatomy_meshes FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "read z anatomy wger map" ON public.z_anatomy_wger_muscle_map;
CREATE POLICY "read z anatomy wger map" ON public.z_anatomy_wger_muscle_map FOR SELECT TO anon, authenticated USING (true);

-- No client policies are intentionally created for sync_state / sync_config.
