-- Phase 1 Exercise Knowledge Graph
-- Extends existing wger + rehab metadata without replacing upstream exercise IDs.
-- AI-generated relationships are candidates only. Runtime recommendations read REVIEWED edges only.

ALTER TABLE public.rehab_exercise_metadata
  ADD COLUMN IF NOT EXISTS movement_family text,
  ADD COLUMN IF NOT EXISTS movement_pattern text,
  ADD COLUMN IF NOT EXISTS training_intents text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS primary_training_intent text,
  ADD COLUMN IF NOT EXISTS strength_demand smallint,
  ADD COLUMN IF NOT EXISTS stability_demand smallint,
  ADD COLUMN IF NOT EXISTS coordination_demand smallint,
  ADD COLUMN IF NOT EXISTS balance_demand smallint,
  ADD COLUMN IF NOT EXISTS rom_demand smallint,
  ADD COLUMN IF NOT EXISTS mobility_demand smallint,
  ADD COLUMN IF NOT EXISTS load_potential smallint,
  ADD COLUMN IF NOT EXISTS support_level text,
  ADD COLUMN IF NOT EXISTS laterality text,
  ADD COLUMN IF NOT EXISTS kinetic_chain text,
  ADD COLUMN IF NOT EXISTS equipment_level smallint,
  ADD COLUMN IF NOT EXISTS skill_level smallint,
  ADD COLUMN IF NOT EXISTS strength_level smallint,
  ADD COLUMN IF NOT EXISTS mobility_requirement smallint,
  ADD COLUMN IF NOT EXISTS classification_status text NOT NULL DEFAULT 'UNCLASSIFIED',
  ADD COLUMN IF NOT EXISTS classification_reason text,
  ADD COLUMN IF NOT EXISTS classification_reviewed_by uuid,
  ADD COLUMN IF NOT EXISTS classification_reviewed_at timestamptz;

ALTER TABLE public.rehab_exercise_metadata
  DROP CONSTRAINT IF EXISTS rehab_movement_family_check,
  ADD CONSTRAINT rehab_movement_family_check CHECK (
    movement_family IS NULL OR movement_family IN
    ('GLUTE','CORE','SCAPULA_SHOULDER','NECK_SHOULDER','HIP','KNEE','ANKLE_FOOT','OTHER')
  ),
  DROP CONSTRAINT IF EXISTS rehab_training_intents_check,
  ADD CONSTRAINT rehab_training_intents_check CHECK (
    training_intents <@ ARRAY[
      'STRENGTH','HYPERTROPHY','ACTIVATION','MOTOR_CONTROL','MOBILITY','STRETCH',
      'RELEASE','BALANCE','POWER','ENDURANCE','WARMUP','RECOVERY'
    ]::text[]
  ),
  DROP CONSTRAINT IF EXISTS rehab_primary_intent_check,
  ADD CONSTRAINT rehab_primary_intent_check CHECK (
    primary_training_intent IS NULL OR primary_training_intent IN
    ('STRENGTH','HYPERTROPHY','ACTIVATION','MOTOR_CONTROL','MOBILITY','STRETCH',
     'RELEASE','BALANCE','POWER','ENDURANCE','WARMUP','RECOVERY')
  ),
  DROP CONSTRAINT IF EXISTS rehab_classification_status_check,
  ADD CONSTRAINT rehab_classification_status_check CHECK (
    classification_status IN ('UNCLASSIFIED','AUTO_SUGGESTED','REVIEWED','REJECTED')
  );

DO $$
DECLARE c text;
BEGIN
  FOREACH c IN ARRAY ARRAY[
    'strength_demand','stability_demand','coordination_demand','balance_demand',
    'rom_demand','mobility_demand','load_potential','equipment_level','skill_level',
    'strength_level','mobility_requirement'
  ] LOOP
    EXECUTE format('ALTER TABLE public.rehab_exercise_metadata DROP CONSTRAINT IF EXISTS %I','rehab_'||c||'_range');
    EXECUTE format('ALTER TABLE public.rehab_exercise_metadata ADD CONSTRAINT %I CHECK (%I IS NULL OR %I BETWEEN 1 AND 5)','rehab_'||c||'_range',c,c);
  END LOOP;
END $$;

INSERT INTO public.rehab_exercise_metadata(exercise_id)
SELECT id FROM public.wger_exercises
ON CONFLICT (exercise_id) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_rehab_movement_family_pattern
  ON public.rehab_exercise_metadata(movement_family,movement_pattern);
CREATE INDEX IF NOT EXISTS idx_rehab_training_intents_gin
  ON public.rehab_exercise_metadata USING gin(training_intents);

CREATE TABLE IF NOT EXISTS public.exercise_relationships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_exercise_id bigint NOT NULL REFERENCES public.wger_exercises(id) ON DELETE CASCADE,
  to_exercise_id bigint NOT NULL REFERENCES public.wger_exercises(id) ON DELETE CASCADE,
  relationship_type text NOT NULL,
  progression_dimension text[] NOT NULL DEFAULT '{}',
  difficulty_delta jsonb NOT NULL DEFAULT '{}'::jsonb,
  required_conditions jsonb NOT NULL DEFAULT '{}'::jsonb,
  contraindications text[] NOT NULL DEFAULT '{}',
  confidence numeric(4,3),
  evidence_level text,
  evidence_source text[] NOT NULL DEFAULT '{}',
  review_status text NOT NULL DEFAULT 'AUTO_SUGGESTED',
  reviewed_by uuid,
  reviewed_at timestamptz,
  rejection_reason text,
  ai_reason text,
  notes text,
  created_by_type text NOT NULL DEFAULT 'AI',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT exercise_relationship_no_self_loop CHECK (from_exercise_id <> to_exercise_id),
  CONSTRAINT exercise_relationship_type_check CHECK (relationship_type IN
    ('PROGRESSION','REGRESSION','ALTERNATIVE','PREPARATION','ACTIVATION','MOBILITY','RELEASE')),
  CONSTRAINT exercise_relationship_dimension_check CHECK (progression_dimension <@ ARRAY[
    'LOAD','VOLUME','ROM','STABILITY','COORDINATION','BALANCE','UNILATERAL','TEMPO',
    'POWER','ENDURANCE','MOTOR_CONTROL','COMPLEXITY']::text[]),
  CONSTRAINT exercise_relationship_review_status_check CHECK
    (review_status IN ('AUTO_SUGGESTED','REVIEWED','REJECTED')),
  CONSTRAINT exercise_relationship_review_requires_reviewer CHECK
    (review_status <> 'REVIEWED' OR (reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)),
  CONSTRAINT exercise_relationship_confidence_range CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
  CONSTRAINT exercise_relationship_evidence_level_check CHECK (evidence_level IS NULL OR evidence_level IN ('A','B','C','D')),
  CONSTRAINT exercise_relationship_unique UNIQUE(from_exercise_id,to_exercise_id,relationship_type)
);

CREATE INDEX IF NOT EXISTS idx_relationship_from_type_status
  ON public.exercise_relationships(from_exercise_id,relationship_type,review_status);
CREATE INDEX IF NOT EXISTS idx_relationship_to_type_status
  ON public.exercise_relationships(to_exercise_id,relationship_type,review_status);
CREATE INDEX IF NOT EXISTS idx_relationship_dimensions_gin
  ON public.exercise_relationships USING gin(progression_dimension);

CREATE TABLE IF NOT EXISTS public.exercise_relationship_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  relationship_id bigint NOT NULL,
  action text NOT NULL,
  actor_id uuid,
  old_row jsonb,
  new_row jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.app_set_updated_at()
RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$
BEGIN NEW.updated_at=now(); RETURN NEW; END; $$;

DROP TRIGGER IF EXISTS trg_exercise_relationship_updated_at ON public.exercise_relationships;
CREATE TRIGGER trg_exercise_relationship_updated_at BEFORE UPDATE ON public.exercise_relationships
FOR EACH ROW EXECUTE FUNCTION public.app_set_updated_at();

CREATE OR REPLACE FUNCTION public.audit_exercise_relationship()
RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$
BEGIN
  INSERT INTO public.exercise_relationship_audit(relationship_id,action,actor_id,old_row,new_row)
  VALUES(COALESCE(NEW.id,OLD.id),TG_OP,NULLIF(current_setting('app.relationship_actor',true),'')::uuid,
    CASE WHEN TG_OP IN ('UPDATE','DELETE') THEN to_jsonb(OLD) END,
    CASE WHEN TG_OP IN ('INSERT','UPDATE') THEN to_jsonb(NEW) END);
  RETURN COALESCE(NEW,OLD);
END; $$;

DROP TRIGGER IF EXISTS trg_exercise_relationship_audit ON public.exercise_relationships;
CREATE TRIGGER trg_exercise_relationship_audit AFTER INSERT OR UPDATE OR DELETE ON public.exercise_relationships
FOR EACH ROW EXECUTE FUNCTION public.audit_exercise_relationship();

CREATE OR REPLACE FUNCTION public.protect_reviewed_exercise_relationship()
RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$
BEGIN
  IF OLD.review_status='REVIEWED' AND COALESCE(current_setting('app.relationship_review_edit',true),'')<>'on' THEN
    RAISE EXCEPTION 'REVIEWED exercise relationships may only be changed through the explicit review workflow';
  END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_protect_reviewed_exercise_relationship ON public.exercise_relationships;
CREATE TRIGGER trg_protect_reviewed_exercise_relationship BEFORE UPDATE OR DELETE ON public.exercise_relationships
FOR EACH ROW EXECUTE FUNCTION public.protect_reviewed_exercise_relationship();

CREATE OR REPLACE FUNCTION public.review_exercise_relationship(
  p_relationship_id bigint,p_action text,p_reviewer uuid,p_patch jsonb DEFAULT '{}'::jsonb,p_rejection_reason text DEFAULT NULL
) RETURNS public.exercise_relationships
LANGUAGE plpgsql SECURITY INVOKER SET search_path=public AS $$
DECLARE v_row public.exercise_relationships; v_action text:=upper(p_action);
BEGIN
  IF p_reviewer IS NULL THEN RAISE EXCEPTION 'reviewer is required'; END IF;
  IF v_action NOT IN ('APPROVE','REJECT','EDIT') THEN RAISE EXCEPTION 'unsupported review action: %',p_action; END IF;
  PERFORM set_config('app.relationship_review_edit','on',true);
  PERFORM set_config('app.relationship_actor',p_reviewer::text,true);
  IF v_action='APPROVE' THEN
    UPDATE public.exercise_relationships SET review_status='REVIEWED',reviewed_by=p_reviewer,reviewed_at=now(),rejection_reason=NULL
    WHERE id=p_relationship_id RETURNING * INTO v_row;
  ELSIF v_action='REJECT' THEN
    UPDATE public.exercise_relationships SET review_status='REJECTED',reviewed_by=p_reviewer,reviewed_at=now(),rejection_reason=p_rejection_reason
    WHERE id=p_relationship_id RETURNING * INTO v_row;
  ELSE
    UPDATE public.exercise_relationships SET
      relationship_type=COALESCE(p_patch->>'relationship_type',relationship_type),
      progression_dimension=CASE WHEN p_patch?'progression_dimension' THEN ARRAY(SELECT jsonb_array_elements_text(p_patch->'progression_dimension')) ELSE progression_dimension END,
      difficulty_delta=CASE WHEN p_patch?'difficulty_delta' THEN p_patch->'difficulty_delta' ELSE difficulty_delta END,
      required_conditions=CASE WHEN p_patch?'required_conditions' THEN p_patch->'required_conditions' ELSE required_conditions END,
      contraindications=CASE WHEN p_patch?'contraindications' THEN ARRAY(SELECT jsonb_array_elements_text(p_patch->'contraindications')) ELSE contraindications END,
      confidence=COALESCE((p_patch->>'confidence')::numeric,confidence),
      evidence_level=CASE WHEN p_patch?'evidence_level' THEN NULLIF(p_patch->>'evidence_level','') ELSE evidence_level END,
      evidence_source=CASE WHEN p_patch?'evidence_source' THEN ARRAY(SELECT jsonb_array_elements_text(p_patch->'evidence_source')) ELSE evidence_source END,
      ai_reason=COALESCE(p_patch->>'ai_reason',ai_reason),notes=CASE WHEN p_patch?'notes' THEN p_patch->>'notes' ELSE notes END,
      review_status='AUTO_SUGGESTED',reviewed_by=NULL,reviewed_at=NULL,rejection_reason=NULL
    WHERE id=p_relationship_id RETURNING * INTO v_row;
  END IF;
  PERFORM set_config('app.relationship_review_edit','off',true);
  PERFORM set_config('app.relationship_actor','',true);
  IF v_row.id IS NULL THEN RAISE EXCEPTION 'relationship not found'; END IF;
  RETURN v_row;
END; $$;
REVOKE ALL ON FUNCTION public.review_exercise_relationship(bigint,text,uuid,jsonb,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.review_exercise_relationship(bigint,text,uuid,jsonb,text) TO service_role;

CREATE TABLE IF NOT EXISTS public.exercise_session_feedback (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  exercise_id bigint NOT NULL REFERENCES public.wger_exercises(id) ON DELETE RESTRICT,
  completed_at timestamptz NOT NULL DEFAULT now(),completion boolean NOT NULL DEFAULT true,
  completion_rate numeric(5,4),reps integer,sets integer,weight numeric(10,3),rpe numeric(4,2),rir numeric(4,2),pain numeric(4,2),
  technique_quality smallint,movement_quality smallint,readiness smallint,fatigue smallint,goal text,
  sharp_pain boolean NOT NULL DEFAULT false,numbness boolean NOT NULL DEFAULT false,tingling boolean NOT NULL DEFAULT false,
  radiating_pain boolean NOT NULL DEFAULT false,joint_pain_worsening boolean NOT NULL DEFAULT false,notes text,created_at timestamptz NOT NULL DEFAULT now(),
  CHECK(completion_rate IS NULL OR completion_rate BETWEEN 0 AND 1),CHECK(rpe IS NULL OR rpe BETWEEN 0 AND 10),
  CHECK(rir IS NULL OR rir BETWEEN 0 AND 10),CHECK(pain IS NULL OR pain BETWEEN 0 AND 10),
  CHECK(technique_quality IS NULL OR technique_quality BETWEEN 1 AND 5),CHECK(movement_quality IS NULL OR movement_quality BETWEEN 1 AND 5),
  CHECK(readiness IS NULL OR readiness BETWEEN 1 AND 5),CHECK(fatigue IS NULL OR fatigue BETWEEN 1 AND 5)
);
CREATE INDEX IF NOT EXISTS idx_feedback_user_exercise_time ON public.exercise_session_feedback(user_id,exercise_id,completed_at DESC);
ALTER TABLE public.exercise_session_feedback ENABLE ROW LEVEL SECURITY;
CREATE POLICY feedback_owner_select ON public.exercise_session_feedback FOR SELECT TO authenticated USING ((select auth.uid())=user_id);
CREATE POLICY feedback_owner_insert ON public.exercise_session_feedback FOR INSERT TO authenticated WITH CHECK ((select auth.uid())=user_id);
CREATE POLICY feedback_owner_update ON public.exercise_session_feedback FOR UPDATE TO authenticated USING ((select auth.uid())=user_id) WITH CHECK ((select auth.uid())=user_id);
REVOKE ALL ON TABLE public.exercise_session_feedback FROM anon,authenticated;
GRANT SELECT,INSERT,UPDATE ON TABLE public.exercise_session_feedback TO authenticated;

ALTER TABLE public.exercise_relationships ENABLE ROW LEVEL SECURITY;
CREATE POLICY app_read_reviewed_exercise_relationships ON public.exercise_relationships FOR SELECT TO anon,authenticated USING (review_status='REVIEWED');
REVOKE ALL ON TABLE public.exercise_relationships FROM anon,authenticated;
GRANT SELECT ON TABLE public.exercise_relationships TO anon,authenticated;
ALTER TABLE public.exercise_relationship_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.exercise_relationship_audit FROM anon,authenticated;

CREATE OR REPLACE VIEW public.exercise_knowledge_view WITH (security_invoker=true) AS
SELECT e.id exercise_id,t.name name_en,e.category_name,r.movement_family,r.movement_pattern,r.training_intents,r.primary_training_intent,
 r.strength_demand,r.stability_demand,r.coordination_demand,r.balance_demand,r.rom_demand,r.mobility_demand,r.load_potential,
 r.support_level,r.laterality,r.kinetic_chain,r.equipment_level,r.skill_level,r.strength_level,r.mobility_requirement,
 r.classification_status,r.classification_reason,COALESCE(pm.primary_muscles,'{}') primary_muscles,
 COALESCE(sm.secondary_muscles,'{}') secondary_muscles,COALESCE(eq.equipment,'{}') equipment
FROM public.wger_exercises e LEFT JOIN public.rehab_exercise_metadata r ON r.exercise_id=e.id
LEFT JOIN LATERAL(SELECT wt.name FROM public.wger_exercise_translations wt WHERE wt.exercise_id=e.id AND wt.language_id=2 ORDER BY wt.id LIMIT 1)t ON true
LEFT JOIN LATERAL(SELECT array_agg(DISTINCT m.name ORDER BY m.name) primary_muscles FROM public.wger_exercise_muscles em JOIN public.wger_muscles m ON m.id=em.muscle_id WHERE em.exercise_id=e.id AND em.role='primary')pm ON true
LEFT JOIN LATERAL(SELECT array_agg(DISTINCT m.name ORDER BY m.name) secondary_muscles FROM public.wger_exercise_muscles em JOIN public.wger_muscles m ON m.id=em.muscle_id WHERE em.exercise_id=e.id AND em.role='secondary')sm ON true
LEFT JOIN LATERAL(SELECT array_agg(DISTINCT q.name ORDER BY q.name) equipment FROM public.wger_exercise_equipment we JOIN public.wger_equipment q ON q.id=we.equipment_id WHERE we.exercise_id=e.id)eq ON true;
GRANT SELECT ON public.exercise_knowledge_view TO anon,authenticated;

CREATE OR REPLACE VIEW public.exercise_graph_validation WITH (security_invoker=true) AS
SELECT 'CIRCULAR_PROGRESSION'::text issue_type,a.id relationship_id,a.from_exercise_id exercise_id,
 jsonb_build_object('from',a.from_exercise_id,'to',a.to_exercise_id,'reverse_edge',b.id) details
FROM public.exercise_relationships a JOIN public.exercise_relationships b ON b.from_exercise_id=a.to_exercise_id AND b.to_exercise_id=a.from_exercise_id
 AND b.relationship_type='PROGRESSION' AND b.review_status IN('AUTO_SUGGESTED','REVIEWED')
WHERE a.relationship_type='PROGRESSION' AND a.review_status IN('AUTO_SUGGESTED','REVIEWED') AND a.id<b.id
UNION ALL
SELECT 'NO_REVIEWED_PROGRESSION',NULL::bigint,r.exercise_id,jsonb_build_object('family',r.movement_family,'pattern',r.movement_pattern)
FROM public.rehab_exercise_metadata r WHERE r.movement_family IN('GLUTE','HIP') AND r.primary_training_intent IN('STRENGTH','HYPERTROPHY','MOTOR_CONTROL','ACTIVATION','BALANCE','POWER')
 AND r.classification_status<>'REJECTED' AND NOT EXISTS(SELECT 1 FROM public.exercise_relationships er WHERE er.from_exercise_id=r.exercise_id AND er.relationship_type='PROGRESSION' AND er.review_status='REVIEWED')
UNION ALL
SELECT 'NO_REVIEWED_REGRESSION',NULL::bigint,r.exercise_id,jsonb_build_object('family',r.movement_family,'pattern',r.movement_pattern)
FROM public.rehab_exercise_metadata r WHERE r.movement_family IN('GLUTE','HIP') AND r.primary_training_intent IN('STRENGTH','HYPERTROPHY','MOTOR_CONTROL','ACTIVATION','BALANCE','POWER')
 AND r.classification_status<>'REJECTED' AND NOT EXISTS(SELECT 1 FROM public.exercise_relationships er WHERE er.from_exercise_id=r.exercise_id AND er.relationship_type='REGRESSION' AND er.review_status='REVIEWED');
REVOKE ALL ON public.exercise_graph_validation FROM anon,authenticated;

CREATE OR REPLACE FUNCTION public.evaluate_exercise_progression(p_exercise_id bigint,p_direction text,p_completed_sessions integer DEFAULT 0,p_completion_rate numeric DEFAULT NULL,p_quality_score numeric DEFAULT NULL,p_pain_score numeric DEFAULT NULL,p_rpe numeric DEFAULT NULL)
RETURNS TABLE(rule_id bigint,next_exercise_id bigint,direction text,priority smallint,criteria_text text,rationale_text text,evidence_claim_id bigint)
LANGUAGE sql STABLE SET search_path=public AS $$
SELECT r.id,r.to_exercise_id,lower(r.relationship_type),COALESCE((r.required_conditions->>'priority')::smallint,50::smallint),r.required_conditions::text,COALESCE(r.notes,r.ai_reason),NULL::bigint
FROM public.exercise_relationships r WHERE r.from_exercise_id=p_exercise_id AND r.relationship_type=upper(p_direction)
 AND upper(p_direction) IN('PROGRESSION','REGRESSION') AND r.review_status='REVIEWED'
 AND p_completed_sessions>=COALESCE((r.required_conditions->>'min_completed_sessions')::int,0)
 AND (NOT(r.required_conditions?'min_completion_rate') OR (p_completion_rate IS NOT NULL AND p_completion_rate>=(r.required_conditions->>'min_completion_rate')::numeric))
 AND (NOT(r.required_conditions?'min_quality_score') OR (p_quality_score IS NOT NULL AND p_quality_score>=(r.required_conditions->>'min_quality_score')::numeric))
 AND (NOT(r.required_conditions?'max_pain_score') OR (p_pain_score IS NOT NULL AND p_pain_score<=(r.required_conditions->>'max_pain_score')::numeric))
ORDER BY COALESCE((r.required_conditions->>'priority')::int,50),r.confidence DESC NULLS LAST,r.id; $$;

-- Main user-level decision engine. It deliberately exhausts in-exercise progression before graph progression.
CREATE OR REPLACE FUNCTION public.decide_exercise_progression(
 p_exercise_id bigint,p_user_id uuid DEFAULT NULL,p_current_reps integer DEFAULT NULL,p_current_sets integer DEFAULT NULL,
 p_current_weight numeric DEFAULT NULL,p_target_rep_max integer DEFAULT NULL,p_target_set_max integer DEFAULT NULL,
 p_goal text DEFAULT NULL,p_need_alternative boolean DEFAULT false,p_in_exercise_progression_exhausted boolean DEFAULT false)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY INVOKER SET search_path=public AS $$
DECLARE v_uid uuid:=COALESCE(p_user_id,auth.uid());v_count int;v_good int;v_completion numeric;v_rpe numeric;v_rir numeric;v_pain numeric;v_tech numeric;v_move numeric;v_readiness numeric;v_fatigue numeric;v_safety boolean;v_edge public.exercise_relationships;
BEGIN
 IF v_uid IS NULL THEN RAISE EXCEPTION 'user is required'; END IF;
 IF auth.uid() IS NOT NULL AND v_uid<>auth.uid() THEN RAISE EXCEPTION 'cannot evaluate another user'; END IF;
 WITH recent AS(SELECT * FROM public.exercise_session_feedback WHERE user_id=v_uid AND exercise_id=p_exercise_id ORDER BY completed_at DESC LIMIT 2)
 SELECT count(*),count(*) FILTER(WHERE completion_rate>=.95 AND COALESCE(rir,0)>=2 AND COALESCE(rpe,10)<=8 AND COALESCE(pain,10)<=2 AND COALESCE(technique_quality,0)>=4 AND COALESCE(movement_quality,0)>=4 AND COALESCE(readiness,0)>=3),
 avg(completion_rate),avg(rpe),avg(rir),avg(pain),avg(technique_quality),avg(movement_quality),avg(readiness),avg(fatigue),bool_or(sharp_pain OR numbness OR tingling OR radiating_pain OR joint_pain_worsening)
 INTO v_count,v_good,v_completion,v_rpe,v_rir,v_pain,v_tech,v_move,v_readiness,v_fatigue,v_safety FROM recent;
 IF COALESCE(v_safety,false) OR COALESCE(v_pain,0)>=4 THEN RETURN jsonb_build_object('decision','RECOVERY','reason','Safety symptom or worsening pain blocks automatic progression','next_exercise_id',NULL,'needs_professional_assessment',true); END IF;
 IF v_count=0 THEN RETURN jsonb_build_object('decision','KEEP','reason','No recent exercise history','next_exercise_id',NULL); END IF;
 IF COALESCE(v_readiness,5)<=2 OR COALESCE(v_fatigue,1)>=4.5 THEN RETURN jsonb_build_object('decision','RECOVERY','reason','Low readiness or high fatigue','next_exercise_id',NULL); END IF;
 IF COALESCE(v_tech,5)<3 OR COALESCE(v_move,5)<3 OR COALESCE(v_pain,0)>2 THEN
  SELECT * INTO v_edge FROM public.exercise_relationships WHERE from_exercise_id=p_exercise_id AND relationship_type='REGRESSION' AND review_status='REVIEWED' ORDER BY confidence DESC NULLS LAST,id LIMIT 1;
  IF v_edge.id IS NOT NULL THEN RETURN jsonb_build_object('decision','REGRESS','reason','Technique/movement quality or pain indicates a reviewed regression','next_exercise_id',v_edge.to_exercise_id,'relationship_id',v_edge.id); END IF;
  RETURN jsonb_build_object('decision','KEEP','reason','Technique or pain needs improvement; no reviewed regression is available','next_exercise_id',NULL);
 END IF;
 IF p_need_alternative THEN
  SELECT * INTO v_edge FROM public.exercise_relationships WHERE from_exercise_id=p_exercise_id AND relationship_type='ALTERNATIVE' AND review_status='REVIEWED' ORDER BY confidence DESC NULLS LAST,id LIMIT 1;
  IF v_edge.id IS NOT NULL THEN RETURN jsonb_build_object('decision','ALTERNATIVE','reason','A reviewed alternative was requested','next_exercise_id',v_edge.to_exercise_id,'relationship_id',v_edge.id); END IF;
 END IF;
 IF v_good<2 THEN RETURN jsonb_build_object('decision','KEEP','reason','Current exercise has not yet met mastery criteria for two consecutive sessions','next_exercise_id',NULL); END IF;
 IF p_current_reps IS NOT NULL AND p_target_rep_max IS NOT NULL AND p_current_reps<p_target_rep_max THEN RETURN jsonb_build_object('decision','REPS_UP','reason','Mastery criteria met; increase repetitions before changing exercise','suggested_reps',p_current_reps+1,'next_exercise_id',NULL); END IF;
 IF COALESCE(p_current_weight,0)>0 AND COALESCE(v_rir,0)>=2 AND COALESCE(v_rpe,10)<=8 THEN RETURN jsonb_build_object('decision','LOAD_UP','reason','Mastery criteria met with reserve available; increase load before changing exercise','next_exercise_id',NULL); END IF;
 IF p_current_sets IS NOT NULL AND p_target_set_max IS NOT NULL AND p_current_sets<p_target_set_max THEN RETURN jsonb_build_object('decision','SETS_UP','reason','Mastery criteria met; increase volume before changing exercise','suggested_sets',p_current_sets+1,'next_exercise_id',NULL); END IF;
 IF NOT p_in_exercise_progression_exhausted THEN RETURN jsonb_build_object('decision','KEEP','reason','Use tempo or ROM progression before changing exercise; graph progression is not yet unlocked','adjustment','TEMPO_OR_ROM','next_exercise_id',NULL); END IF;
 SELECT * INTO v_edge FROM public.exercise_relationships WHERE from_exercise_id=p_exercise_id AND relationship_type='PROGRESSION' AND review_status='REVIEWED'
 ORDER BY CASE WHEN p_goal IS NOT NULL AND p_goal=ANY(progression_dimension) THEN 0 ELSE 1 END,confidence DESC NULLS LAST,id LIMIT 1;
 IF v_edge.id IS NOT NULL THEN RETURN jsonb_build_object('decision','PROGRESS','reason','In-exercise progression exhausted; selected from REVIEWED exercise graph','next_exercise_id',v_edge.to_exercise_id,'relationship_id',v_edge.id,'dimensions',v_edge.progression_dimension); END IF;
 RETURN jsonb_build_object('decision','KEEP','reason','No REVIEWED progression edge is available','next_exercise_id',NULL);
END; $$;
REVOKE ALL ON FUNCTION public.decide_exercise_progression(bigint,uuid,integer,integer,numeric,integer,integer,text,boolean,boolean) FROM PUBLIC,anon;
GRANT EXECUTE ON FUNCTION public.decide_exercise_progression(bigint,uuid,integer,integer,numeric,integer,integer,text,boolean,boolean) TO authenticated,service_role;
