-- Phase 1 GLUTE + HIP classification seed.
-- All rows are AUTO_SUGGESTED until a human reviews the classification.
-- Existing wger exercise IDs are reused without modification.

INSERT INTO public.rehab_exercise_metadata (
exercise_id,movement_family,movement_pattern,training_intents,primary_training_intent,
strength_demand,stability_demand,coordination_demand,balance_demand,rom_demand,mobility_demand,load_potential,
support_level,laterality,kinetic_chain,equipment_level,skill_level,strength_level,mobility_requirement,classification_status,classification_reason
) VALUES
(265,'GLUTE','HIP_EXTENSION',ARRAY['ACTIVATION','STRENGTH','MOTOR_CONTROL'],'STRENGTH',1,1,1,1,2,1,2,'HIGH_SUPPORT','BILATERAL','CLOSED',1,1,1,1,'AUTO_SUGGESTED','Foundational bilateral bridge.'),
(294,'GLUTE','HIP_EXTENSION',ARRAY['STRENGTH','HYPERTROPHY'],'STRENGTH',3,2,2,1,3,2,5,'PARTIAL_SUPPORT','BILATERAL','CLOSED',4,2,3,2,'AUTO_SUGGESTED','Barbell hip thrust with high load potential.'),
(1642,'GLUTE','HIP_EXTENSION',ARRAY['STRENGTH','HYPERTROPHY'],'STRENGTH',2,2,2,1,3,2,3,'PARTIAL_SUPPORT','BILATERAL','CLOSED',2,2,2,2,'AUTO_SUGGESTED','Dumbbell hip thrust with moderate load potential.'),
(1234,'GLUTE','HIP_EXTENSION',ARRAY['STRENGTH','MOTOR_CONTROL'],'STRENGTH',3,4,3,3,3,2,3,'PARTIAL_SUPPORT','UNILATERAL','CLOSED',2,3,3,2,'AUTO_SUGGESTED','Single-leg hip thrust adds unilateral stability.'),
(1528,'GLUTE','HIP_EXTENSION',ARRAY['STRENGTH','HYPERTROPHY'],'STRENGTH',3,1,1,1,3,1,5,'EXTERNAL_STABILITY','BILATERAL','CLOSED',4,1,3,1,'AUTO_SUGGESTED','Glute-drive style movement with high support and load potential.'),
(1131,'GLUTE','HIP_EXTENSION',ARRAY['STRENGTH','ACTIVATION'],'STRENGTH',2,2,2,2,2,1,3,'PARTIAL_SUPPORT','UNILATERAL','OPEN',3,2,2,1,'AUTO_SUGGESTED','Cable hip extension with unilateral control.'),
(1132,'GLUTE','HIP_EXTENSION',ARRAY['STRENGTH','ACTIVATION'],'STRENGTH',2,1,1,1,2,1,4,'EXTERNAL_STABILITY','UNILATERAL','OPEN',4,1,2,1,'AUTO_SUGGESTED','Machine hip extension with external stability.'),
(990,'GLUTE','HIP_EXTENSION',ARRAY['ACTIVATION','MOTOR_CONTROL'],'ACTIVATION',1,2,2,1,2,1,1,'HIGH_SUPPORT','UNILATERAL','OPEN',1,1,1,1,'AUTO_SUGGESTED','Quadruped kickback for low-load activation.'),
(1616,'GLUTE','HIP_EXTENSION',ARRAY['STRENGTH','ACTIVATION'],'STRENGTH',2,3,3,2,2,1,2,'HIGH_SUPPORT','UNILATERAL','OPEN',2,2,2,1,'AUTO_SUGGESTED','Loaded donkey kick adds load and trunk control.'),
(1842,'GLUTE','HIP_EXTERNAL_ROTATION',ARRAY['ACTIVATION','MOTOR_CONTROL'],'ACTIVATION',1,1,2,1,2,1,2,'HIGH_SUPPORT','UNILATERAL','OPEN',2,1,1,1,'AUTO_SUGGESTED','Banded clamshell for hip external-rotation activation.'),
(1096,'GLUTE','HIP_ABDUCTION',ARRAY['ACTIVATION','BALANCE','MOTOR_CONTROL'],'ACTIVATION',1,3,2,3,2,1,1,'LOW_SUPPORT','UNILATERAL','OPEN',1,2,1,1,'AUTO_SUGGESTED','Standing abduction adds balance demand.'),
(1748,'GLUTE','HIP_ABDUCTION',ARRAY['STRENGTH','HYPERTROPHY'],'STRENGTH',2,1,1,1,2,1,4,'EXTERNAL_STABILITY','BILATERAL','OPEN',4,1,2,1,'AUTO_SUGGESTED','Machine hip abduction is supported and loadable.'),
(2665,'GLUTE','HIP_ABDUCTION',ARRAY['ACTIVATION','MOTOR_CONTROL','ENDURANCE'],'ACTIVATION',1,3,3,3,2,1,2,'LOW_SUPPORT','BILATERAL','CLOSED',2,2,1,1,'AUTO_SUGGESTED','Monster walk adds locomotor frontal-plane control.'),
(2618,'GLUTE','HIP_ABDUCTION',ARRAY['ACTIVATION','MOTOR_CONTROL','ENDURANCE'],'MOTOR_CONTROL',1,3,3,3,2,1,2,'LOW_SUPPORT','BILATERAL','CLOSED',2,2,1,1,'AUTO_SUGGESTED','Lateral band steps emphasize control during stepping.'),
(2449,'HIP','HIP_EXTERNAL_ROTATION',ARRAY['MOTOR_CONTROL','MOBILITY','ACTIVATION'],'MOTOR_CONTROL',1,1,3,1,3,3,1,'HIGH_SUPPORT','UNILATERAL','OPEN',1,2,1,3,'AUTO_SUGGESTED','Controlled hip rotation drill.'),
(2613,'HIP','HIP_MOBILITY',ARRAY['MOBILITY','MOTOR_CONTROL','WARMUP'],'MOBILITY',1,2,3,1,4,4,1,'HIGH_SUPPORT','BILATERAL','OPEN',1,2,1,4,'AUTO_SUGGESTED','90/90 switches train active hip rotation.'),
(2614,'HIP','HIP_ADDUCTION',ARRAY['MOBILITY','WARMUP'],'MOBILITY',1,1,2,1,4,4,1,'HIGH_SUPPORT','BILATERAL','OPEN',1,1,1,4,'AUTO_SUGGESTED','Adductor mobility drill.'),
(1843,'HIP','HIP_ADDUCTION',ARRAY['STRETCH','MOBILITY'],'STRETCH',1,1,1,1,4,4,1,'HIGH_SUPPORT','BILATERAL','OPEN',1,1,1,4,'AUTO_SUGGESTED','Supported adductor stretch.'),
(1844,'HIP','HIP_ADDUCTION',ARRAY['STRETCH','MOBILITY'],'STRETCH',1,1,1,1,5,5,1,'HIGH_SUPPORT','BILATERAL','OPEN',1,1,1,5,'AUTO_SUGGESTED','Higher-ROM adductor stretch.'),
(1867,'HIP','HIP_MOBILITY',ARRAY['STRETCH','MOBILITY'],'STRETCH',1,1,1,2,4,4,1,'PARTIAL_SUPPORT','UNILATERAL','OPEN',1,1,1,4,'AUTO_SUGGESTED','Hip-flexor mobility drill.'),
(2525,'HIP','HIP_MOBILITY',ARRAY['STRETCH','MOBILITY'],'STRETCH',1,2,2,2,5,5,1,'PARTIAL_SUPPORT','UNILATERAL','OPEN',2,2,1,5,'AUTO_SUGGESTED','High hip-extension mobility demand.'),
(1872,'HIP','HIP_EXTERNAL_ROTATION',ARRAY['STRETCH','MOBILITY'],'STRETCH',1,1,2,1,5,5,1,'HIGH_SUPPORT','UNILATERAL','OPEN',1,2,1,5,'AUTO_SUGGESTED','High passive hip rotation ROM demand.'),
(1869,'GLUTE','HIP_EXTERNAL_ROTATION',ARRAY['STRETCH','MOBILITY'],'STRETCH',1,1,1,1,4,4,1,'HIGH_SUPPORT','UNILATERAL','OPEN',1,1,1,4,'AUTO_SUGGESTED','Supported figure-four glute stretch.'),
(1862,'HIP','HIP_MOBILITY',ARRAY['MOBILITY','WARMUP'],'MOBILITY',1,2,2,2,3,3,1,'LOW_SUPPORT','BILATERAL','OPEN',1,1,1,3,'AUTO_SUGGESTED','Dynamic multi-planar hip mobility.'),
(1670,'HIP','HIP_MOBILITY',ARRAY['MOBILITY','WARMUP'],'WARMUP',1,3,3,3,4,4,1,'LOW_SUPPORT','UNILATERAL','OPEN',1,2,1,4,'AUTO_SUGGESTED','Dynamic sagittal hip ROM with balance.'),
(1395,'HIP','HIP_MOBILITY',ARRAY['MOBILITY','WARMUP'],'WARMUP',1,3,3,3,4,4,1,'LOW_SUPPORT','UNILATERAL','OPEN',1,2,1,4,'AUTO_SUGGESTED','Dynamic cross-body hip ROM with balance.'),
(1859,'GLUTE','SOFT_TISSUE_RELEASE',ARRAY['RELEASE','RECOVERY'],'RELEASE',1,2,2,1,2,2,1,'HIGH_SUPPORT','BILATERAL','N/A',2,1,1,1,'AUTO_SUGGESTED','Release/recovery modality, not a joint movement pattern.'),
(1860,'HIP','SOFT_TISSUE_RELEASE',ARRAY['RELEASE','RECOVERY'],'RELEASE',1,2,2,1,2,2,1,'HIGH_SUPPORT','BILATERAL','N/A',2,1,1,1,'AUTO_SUGGESTED','Release/recovery modality, not a joint movement pattern.'),
(1578,'HIP','HIP_HINGE',ARRAY['MOTOR_CONTROL','STRENGTH'],'MOTOR_CONTROL',1,2,3,2,3,2,3,'LOW_SUPPORT','BILATERAL','CLOSED',3,2,1,2,'AUTO_SUGGESTED','Foundational hip-hinge pattern.'),
(1392,'HIP','HIP_HINGE',ARRAY['STRENGTH','MOTOR_CONTROL'],'STRENGTH',2,2,3,2,3,2,2,'LOW_SUPPORT','BILATERAL','CLOSED',1,2,2,2,'AUTO_SUGGESTED','Good morning adds posterior-chain strength demand.'),
(1370,'HIP','HIP_HINGE',ARRAY['STRENGTH','HYPERTROPHY'],'STRENGTH',3,2,2,2,3,2,4,'LOW_SUPPORT','BILATERAL','CLOSED',2,2,3,2,'AUTO_SUGGESTED','Loaded bilateral hinge.'),
(1652,'HIP','HIP_HINGE',ARRAY['STRENGTH','HYPERTROPHY'],'STRENGTH',3,2,3,2,4,3,4,'LOW_SUPPORT','BILATERAL','CLOSED',2,3,3,3,'AUTO_SUGGESTED','RDL adds posterior-chain ROM under load.'),
(1688,'HIP','HIP_HINGE',ARRAY['STRENGTH','MOTOR_CONTROL'],'STRENGTH',3,3,3,3,4,3,4,'LOW_SUPPORT','STAGGERED','CLOSED',3,3,3,3,'AUTO_SUGGESTED','Kickstand RDL adds asymmetric stability.'),
(1641,'HIP','HIP_HINGE',ARRAY['STRENGTH','BALANCE','MOTOR_CONTROL'],'STRENGTH',3,5,4,5,4,3,3,'LOW_SUPPORT','UNILATERAL','CLOSED',3,4,3,3,'AUTO_SUGGESTED','Single-leg deadlift has high balance/stability demand.'),
(1751,'GLUTE','HIP_HINGE',ARRAY['STRENGTH','MOTOR_CONTROL'],'STRENGTH',2,2,2,2,3,2,4,'LOW_SUPPORT','BILATERAL','CLOSED',3,2,2,2,'AUTO_SUGGESTED','Cable pull-through loads hip extension.'),
(331,'GLUTE','HIP_HINGE',ARRAY['POWER','STRENGTH','ENDURANCE'],'POWER',3,3,4,3,3,2,4,'LOW_SUPPORT','BILATERAL','CLOSED',2,4,3,2,'AUTO_SUGGESTED','Ballistic hinge with high timing/power demand.'),
(1088,'HIP','HIP_HINGE',ARRAY['STRENGTH','HYPERTROPHY'],'STRENGTH',3,2,2,2,3,3,4,'LOW_SUPPORT','BILATERAL','CLOSED',2,2,3,3,'AUTO_SUGGESTED','Sumo stance loaded hinge.'),
(1612,'HIP','HIP_HINGE',ARRAY['STRENGTH','HYPERTROPHY'],'STRENGTH',3,2,2,2,3,3,4,'LOW_SUPPORT','BILATERAL','CLOSED',2,2,3,3,'AUTO_SUGGESTED','Kettlebell sumo hinge.'),
(1312,'HIP','SQUAT',ARRAY['STRENGTH','MOTOR_CONTROL'],'STRENGTH',2,2,2,2,3,3,1,'LOW_SUPPORT','BILATERAL','CLOSED',1,1,2,3,'AUTO_SUGGESTED','Foundational bodyweight squat.'),
(203,'HIP','SQUAT',ARRAY['STRENGTH','MOTOR_CONTROL'],'STRENGTH',2,2,2,2,3,3,3,'LOW_SUPPORT','BILATERAL','CLOSED',2,2,2,3,'AUTO_SUGGESTED','Goblet squat adds anterior load.'),
(1640,'HIP','SQUAT',ARRAY['STRENGTH','HYPERTROPHY'],'STRENGTH',3,2,3,2,4,3,3,'LOW_SUPPORT','BILATERAL','CLOSED',2,3,3,3,'AUTO_SUGGESTED','Dumbbell front squat adds load/trunk demand.'),
(257,'HIP','SQUAT',ARRAY['STRENGTH','HYPERTROPHY'],'STRENGTH',4,3,3,2,4,4,5,'LOW_SUPPORT','BILATERAL','CLOSED',4,4,4,4,'AUTO_SUGGESTED','Barbell front squat has high load/mobility demand.'),
(1801,'HIP','SQUAT',ARRAY['STRENGTH','HYPERTROPHY'],'STRENGTH',4,3,3,2,4,3,5,'LOW_SUPPORT','BILATERAL','CLOSED',4,4,4,3,'AUTO_SUGGESTED','Barbell full squat supports high load and ROM.'),
(977,'HIP','SQUAT',ARRAY['STRENGTH','MOTOR_CONTROL'],'STRENGTH',2,2,2,2,2,2,2,'EXTERNAL_STABILITY','BILATERAL','CLOSED',2,1,2,2,'AUTO_SUGGESTED','Box target reduces ROM uncertainty.'),
(1407,'HIP','SQUAT',ARRAY['MOBILITY','STRENGTH','MOTOR_CONTROL'],'MOBILITY',2,4,4,4,5,5,2,'LOW_SUPPORT','ALTERNATING','CLOSED',1,4,2,5,'AUTO_SUGGESTED','Frontal-plane squat with high adductor/hip mobility demand.'),
(2662,'HIP','SQUAT',ARRAY['STRENGTH','MOTOR_CONTROL'],'STRENGTH',4,3,4,2,4,3,5,'LOW_SUPPORT','BILATERAL','CLOSED',4,4,4,3,'AUTO_SUGGESTED','Paused squat increases positional control.'),
(456,'HIP','SINGLE_LEG_STABILITY',ARRAY['STRENGTH','BALANCE','MOTOR_CONTROL'],'STRENGTH',4,5,5,5,5,5,2,'LOW_SUPPORT','UNILATERAL','CLOSED',1,5,4,5,'AUTO_SUGGESTED','Pistol squat is high-demand unilateral strength/balance.'),
(1935,'HIP','SQUAT',ARRAY['STRENGTH','HYPERTROPHY'],'STRENGTH',4,2,2,2,4,3,5,'LOW_SUPPORT','BILATERAL','CLOSED',5,3,4,3,'AUTO_SUGGESTED','Belt squat permits high lower-body loading.'),
(984,'HIP','LUNGE',ARRAY['STRENGTH','MOTOR_CONTROL'],'STRENGTH',2,3,3,3,3,3,1,'LOW_SUPPORT','ALTERNATING','CLOSED',1,2,2,3,'AUTO_SUGGESTED','Foundational bodyweight lunge.'),
(1102,'HIP','LUNGE',ARRAY['STRENGTH','MOTOR_CONTROL'],'STRENGTH',2,3,3,3,3,3,1,'LOW_SUPPORT','ALTERNATING','CLOSED',1,2,2,3,'AUTO_SUGGESTED','Bodyweight reverse lunge.'),
(205,'HIP','LUNGE',ARRAY['STRENGTH','HYPERTROPHY'],'STRENGTH',3,3,3,3,3,3,4,'LOW_SUPPORT','ALTERNATING','CLOSED',2,3,3,3,'AUTO_SUGGESTED','Loaded dumbbell lunge.'),
(206,'HIP','LUNGE',ARRAY['STRENGTH','HYPERTROPHY','ENDURANCE'],'STRENGTH',3,4,4,4,3,3,4,'LOW_SUPPORT','ALTERNATING','CLOSED',2,3,3,3,'AUTO_SUGGESTED','Walking lunge adds locomotor coordination.'),
(1651,'HIP','LUNGE',ARRAY['STRENGTH','HYPERTROPHY'],'STRENGTH',3,3,3,3,3,3,4,'LOW_SUPPORT','ALTERNATING','CLOSED',2,3,3,3,'AUTO_SUGGESTED','Loaded reverse lunge.'),
(1366,'HIP','LUNGE',ARRAY['STRENGTH','HYPERTROPHY'],'STRENGTH',3,4,3,4,4,3,4,'LOW_SUPPORT','STAGGERED','CLOSED',2,3,3,3,'AUTO_SUGGESTED','Split squat increases unilateral loading without stepping.'),
(1706,'HIP','LUNGE',ARRAY['STRENGTH','HYPERTROPHY'],'STRENGTH',4,4,4,4,5,4,4,'PARTIAL_SUPPORT','STAGGERED','CLOSED',3,4,4,4,'AUTO_SUGGESTED','Rear-foot elevation increases ROM/stability demand.'),
(981,'HIP','STEP',ARRAY['STRENGTH','MOTOR_CONTROL','BALANCE'],'STRENGTH',2,4,3,4,4,3,2,'PARTIAL_SUPPORT','ALTERNATING','CLOSED',2,3,2,3,'AUTO_SUGGESTED','Step-up adds unilateral concentric control and balance.'),
(722,'HIP','STEP',ARRAY['STRENGTH','HYPERTROPHY','BALANCE'],'STRENGTH',3,4,3,4,4,3,4,'PARTIAL_SUPPORT','ALTERNATING','CLOSED',3,3,3,3,'AUTO_SUGGESTED','Weighted step-up adds external load.'),
(2447,'HIP','SINGLE_LEG_STABILITY',ARRAY['MOTOR_CONTROL','BALANCE','MOBILITY'],'MOTOR_CONTROL',2,5,5,5,5,5,2,'LOW_SUPPORT','UNILATERAL','CLOSED',2,5,2,5,'AUTO_SUGGESTED','Hip airplane has high rotational single-leg control demand.'),
(1141,'HIP','SINGLE_LEG_STABILITY',ARRAY['BALANCE','MOTOR_CONTROL'],'MOTOR_CONTROL',2,5,4,5,3,2,1,'LOW_SUPPORT','UNILATERAL','CLOSED',1,4,2,2,'AUTO_SUGGESTED','Arabesque requires single-leg posterior-chain control.'),
(1948,'HIP','SINGLE_LEG_STABILITY',ARRAY['STRENGTH','BALANCE','MOTOR_CONTROL'],'STRENGTH',3,5,4,5,4,4,2,'PARTIAL_SUPPORT','UNILATERAL','CLOSED',2,4,3,4,'AUTO_SUGGESTED','Single-leg box squat combines unilateral squat strength with a target.')
ON CONFLICT (exercise_id) DO UPDATE SET
movement_family=EXCLUDED.movement_family,movement_pattern=EXCLUDED.movement_pattern,training_intents=EXCLUDED.training_intents,
primary_training_intent=EXCLUDED.primary_training_intent,strength_demand=EXCLUDED.strength_demand,stability_demand=EXCLUDED.stability_demand,
coordination_demand=EXCLUDED.coordination_demand,balance_demand=EXCLUDED.balance_demand,rom_demand=EXCLUDED.rom_demand,
mobility_demand=EXCLUDED.mobility_demand,load_potential=EXCLUDED.load_potential,support_level=EXCLUDED.support_level,
laterality=EXCLUDED.laterality,kinetic_chain=EXCLUDED.kinetic_chain,equipment_level=EXCLUDED.equipment_level,
skill_level=EXCLUDED.skill_level,strength_level=EXCLUDED.strength_level,mobility_requirement=EXCLUDED.mobility_requirement,
classification_status='AUTO_SUGGESTED',classification_reason=EXCLUDED.classification_reason,updated_at=now();